version: '3'
services:

  bitbucket:    # Bitbucket Server
    image: "atlassian/bitbucket-server:5.10.2"
    container_name: bitbucket
    restart: always
    ports:
      - "7990:7990"
      - "7999:7999"
    environment:
      - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket/
    volumes:
      - ./bitbucket-data:/var/atlassian/application-data/bitbucket

   jira:        # Jira Core Server
     image: cptactionhank/atlassian-jira:7.12.2
     container_name: jira
     restart: always
     ports:
       - "6080:8080"
     links:
       - database
     volumes:
       - ./jira-data:/var/atlassian/application-data/jira

   confluence:  # Confluence Server
     image: cptactionhank/atlassian-confluence:6.12.0
     container_name: confluence
     restart: always
     ports:
       - "8090:8090"
     links:
       - database
     volumes:
       - ./confluence-data:/var/atlassian/application-data/confluence

  database:     # Database Server
    image: postgres:9.6
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: <input_your_username>
      POSTGRES_PASSWORD: <input_your_password>
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data

volumes:
  bitbucket-data:
  jira-data:
  confluence-data:
  postgresql-data: